Vibrio aerogenes
Vibrio agarilyticus
Vibrio albus
Vibrio algicola
Vibrio alginolyticus
Vibrio algivorus
Vibrio aquaticus
Vibrio artabrorum
Vibrio_A stylophorae
Vibrio bathopelagicus
Vibrio breoganii
Vibrio campbellii
Vibrio chagasii
Vibrio chagasii_A
Vibrio cidicii
Vibrio cincinnatiensis
Vibrio cincinnatiensis_A
Vibrio comitans
Vibrio coralliirubri
Vibrio crassostreae
Vibrio crassostreae_C
Vibrio cyclitrophicus
Vibrio cyclitrophicus_A
Vibrio diabolicus
Vibrio diazotrophicus
Vibrio echinoideorum
Vibrio europaeus
Vibrio fluvialis
Vibrio fortis
Vibrio fortis_A
Vibrio furnissii
Vibrio gallaecicus
Vibrio gazogenes
Vibrio gazogenes_A
Vibrio gigantis
Vibrio halioticoli
Vibrio hangzhouensis
Vibrio harveyi
Vibrio hippocampi
Vibrio hyugaensis
Vibrio ichthyoenteri
Vibrio ishigakensis
Vibrio japonicus
Vibrio jasicida
Vibrio kanaloae
Vibrio lentus
Vibrio lentus_A
Vibrio litoralis
Vibrio maerlii
Vibrio mangrovi
Vibrio marinisediminis
Vibrio maritimus_B
Vibrio mediterranei
Vibrio metschnikovii
Vibrio mytili
Vibrio natriegens
Vibrio navarrensis
Vibrio nigripulchritudo
Vibrio orientalis
Vibrio ouci
Vibrio owensii
Vibrio palustris
Vibrio panuliri
Vibrio parahaemolyticus
Vibrio penaeicida
Vibrio penaeicida_A
Vibrio plantisponsor
Vibrio pomeroyi
Vibrio ponticus
Vibrio porteresiae
Vibrio proteolyticus
Vibrio quintilis
Vibrio renipiscarius
Vibrio rhizosphaerae
Vibrio rotiferianus
Vibrio ruber
Vibrio salinus
Vibrio scophthalmi
Vibrio sinaloensis_B
Vibrio sinensis
Vibrio sp000171815
Vibrio sp000287055
Vibrio sp000316985
Vibrio sp000960595
Vibrio sp001506075
Vibrio sp001874155
Vibrio sp002100145
Vibrio sp002342735
Vibrio sp002812955
Vibrio sp002873395
Vibrio sp002877365
Vibrio sp013114545
Vibrio sp013369385
Vibrio sp014596725
Vibrio sp014694455
Vibrio sp015278125
Vibrio sp018223135
Vibrio sp021726515
Vibrio sp022397955
Vibrio sp023634655
Vibrio sp023716565
Vibrio sp023716665
Vibrio sp903986855
Vibrio spartinae
Vibrio splendidus
Vibrio splendidus_F
Vibrio taketomensis
Vibrio tapetis
Vibrio toranzoniae
Vibrio ulleungensis
Vibrio viridaestus
Vibrio vulnificus
Vibrio xiamenensis
Vibrio ziniensis
